### ISSUE TITLE
Make It Faster

### ISSUE THREAD

**Issue by phish7381** [jnvsor/TabNukerNuker#1]
you can use something like this to make it faster https://github.com/phishontop/sockets-wrapper

**Comment by jnvsor** [comment]
I see your account exists just to spam this message to any repository you can find with "Nuker" in it, regardless of how nonsensical it is. 288 identical issues at random repos in a few days? Really?

I'm sure this has nothing to do with your namesake @phishontop creating that repo a few days ago hmm?
